### ISSUE TITLE
Cannot import honeybee.model

### ISSUE THREAD

**Issue by wassimj** [ladybug-tools/lbt-honeybee#752]
I am getting the following error regarding honeybee.model. What am I missing? Thanks
pip install honeybee
python 3.10
```
>>> import honeybee
>>> from honeybee.model import Model
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
ModuleNotFoundError: No module named 'honeybee.model'
```

**Comment by mostaphaRoudsari** [comment]
Hi @wassimj,

Try `pip install -U honeybee-core` - or try one of the extensions which will install honeybee-core -> `pip install honeybee-energy -U`
